name: moodtunes
  - pip:
      - absl-py==2.1.0
      - accelerate==1.1.1
      - aiohttp==3.11.2
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - faiss-cpu==1.9.0
      - filelock==3.16.1
      - flatbuffers==24.3.25
      - fsspec==2024.10.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - greenlet==3.1.1
      - grpcio==1.68.0
      - h5py==3.12.1
      - httpx-sse==0.4.0
      - jiter==0.7.1
      - jsonpatch==1.33
      - keras==3.6.0
      - langchain==0.3.7
      - langchain-community==0.3.7
      - langchain-core==0.3.19
      - langchain-openai==0.2.8
      - langchain-text-splitters==0.3.2
      - langsmith==0.1.143
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - marshmallow==3.23.1
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - mypy-extensions==1.0.0
      - namex==0.0.8
      - neo4j==5.26.0
      - neo4j-graphrag==1.2.1
      - networkx==3.4.2
      - openai==1.54.4
      - opt-einsum==3.4.0
      - optree==0.13.1
      - orjson==3.10.11
      - peft==0.13.2
      - protobuf==5.28.3
      - pyaudio==0.2.11
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydantic-settings==2.6.1
      - python-dotenv==1.0.1
      - pytz==2024.2
      - regex==2024.11.6
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - sqlalchemy==2.0.35
      - sympy==1.13.1
      - tenacity==9.0.0
      - termcolor==2.5.0
      - tf-keras==2.18.0
      - tiktoken==0.8.0
      - tokenizers==0.20.3
      - torch==2.5.1
      - triton==3.1.0
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - wrapt==1.16.0
      - yarl==1.17.1

